export { WelcomeEmail } from './templates/WelcomeEmail'
export { AdminLoginEmail } from './templates/AdminLoginEmail'
export { PasswordResetEmail } from './templates/PasswordResetEmail'
export { sendEmail, FROM_ADDRESS } from './lib/resend'
export type { WelcomeEmailProps } from './templates/WelcomeEmail'
export type { AdminLoginEmailProps } from './templates/AdminLoginEmail'
export type { PasswordResetEmailProps } from './templates/PasswordResetEmail'
export type { SendEmailOptions } from './lib/resend'
